services:
  app:
    build:
      context: .
      dockerfile: dockerfile/Dev.Dockerfile
    ports:
      - 7860:7860
    command:
      - python
      - src/gradio_app.py
    volumes:
      - ./src/:/app/src/
      - ./models/:/app/models/
      - ./config_debug.json:/app/config.json
