services:
  app:
    build:
      context: services/backend-fastapi
      dockerfile: dockerfile/Dev.Dockerfile
    ports:
      - 8000:5000
    entrypoint:
      - uvicorn
      - src.main:app
      - --reload
      - --host
      - 0.0.0.0
      - --port
      - "5000"
    volumes:
      - ./services/backend-fastapi/src/:/app/src/
      - ./services/backend-fastapi/config.json:/app/config.json
