services:
  app:
    build:
      context: .
      dockerfile: dockerfile/Dev.Dockerfile
    ports:
      - 8000:5000
    command:
      - uvicorn
      - src.app:app
      - --reload
      - --host
      - 0.0.0.0
      - --port
      - "5000"
    volumes:
      - ./src/:/app/src/
      - ./models/:/app/models/
      - ./config_debug.json:/app/config.json
